#Config file for passwd as a service
#Specify paths for passwd and groups files
use_test = false
port = "8080"

[files]
    [files.deploy]
        [files.deploy.users]
        path = '/etc/passwd'

        [files.deploy.groups]
        path = '/etc/group'
    [files.test]
        [files.test.users]
        path = './files/passwd'

        [files.test.groups]
        path = './files/group'
