#Config file for passwd as a service
#Specify paths for passwd and groups files
use_test = false
port = "8080"

[files]
    [files.deploy]
        passwd = '/etc/passwd'
        group = '/etc/group'
    [files.test]
        passwd = './files/passwd'
        group =  './files/group'

